filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/combined-*.log
      - /logs/error-*.log
      - /logs/http-*.log
    json.keys_under_root: true
    json.add_error_key: true
    fields:
      application: rez-merchant-backend
      environment: ${ENVIRONMENT:development}

  - type: docker
    enabled: true
    containers.ids:
      - '*'
    processors:
      - add_docker_metadata: ~

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

setup.kibana:
  host: "kibana:5601"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "filebeat-rez-combined-%{+yyyy.MM.dd}"
      when.contains:
        log.file.path: "combined"
    - index: "filebeat-rez-error-%{+yyyy.MM.dd}"
      when.contains:
        log.file.path: "error"
    - index: "filebeat-rez-http-%{+yyyy.MM.dd}"
      when.contains:
        log.file.path: "http"

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
